<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer Due Report - {{ $branch->name }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Courier New', monospace; font-size: 13px; padding: 10px; color: #000; }
        .header { text-align: center; margin-bottom: 10px; border-bottom: 2px solid #333; padding-bottom: 6px; }
        .header h1 { font-size: 18px; font-weight: bold; }
        .header p { font-size: 12px; color: #555; margin-top: 2px; }
        .print-info { display: flex; justify-content: space-between; font-size: 11px; margin-bottom: 6px; color: #555; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
        th { background: #e0e0e0; font-size: 11px; font-weight: bold; text-align: center; padding: 4px; border: 1px solid #999; }
        td { font-size: 11px; padding: 3px 4px; border: 1px solid #ccc; }
        .text-left { text-align: left; }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .summary { margin-top: 8px; border-top: 2px solid #333; padding-top: 6px; }
        .summary-row { display: flex; justify-content: flex-end; padding: 2px 0; font-size: 12px; }
        .summary-row .label { font-weight: bold; margin-right: 10px; }
        .summary-row .value { font-weight: bold; min-width: 100px; text-align: right; }
        .footer { text-align: center; font-size: 10px; color: #888; margin-top: 12px; border-top: 1px solid #ccc; padding-top: 5px; }
        @media print {
            body { padding: 5px; }
            @page { size: landscape; margin: 8mm; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Customer Due Report</h1>
        <p>{{ $branch->name }} | BM Umrah Booking System</p>
    </div>

    <div class="print-info">
        <span>Generated: {{ now()->format('d-M-Y h:i A') }}</span>
        <span>Generated by: {{ auth()->user()->name }}</span>
    </div>

    @if($dateFrom || $dateTo)
    <div class="print-info" style="border:1px solid #ccc;padding:4px 6px;background:#f9f9f9;margin-bottom:6px;">
        <span>Date Range: {{ $dateFrom ?: 'Start' }} to {{ $dateTo ?: 'End' }}</span>
    </div>
    @endif

    <table>
        <thead>
            <tr>
                <th>Customer Name</th>
                <th>Mobile</th>
                <th>Invoice ID</th>
                <th>Ticket Date</th>
                <th>Total Package</th>
                <th>Paid</th>
                <th>Due</th>
            </tr>
        </thead>
        <tbody>
            @forelse($customers as $row)
            <tr>
                <td class="text-left">{{ $row['name'] }}</td>
                <td class="text-center">{{ $row['mobile'] }}</td>
                <td class="text-center">{{ $row['invoiceId'] }}</td>
                <td class="text-center">{{ $row['ticketDate'] }}</td>
                <td class="text-right">{{ number_format($row['totalPackage'], 2) }}</td>
                <td class="text-right">{{ number_format($row['paid'], 2) }}</td>
                <td class="text-right">{{ number_format($row['due'], 2) }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="7" class="text-center" style="padding:15px;">No customer due data found</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    @if(count($customers) > 0)
    <div class="summary">
        @php
            $totalPackage = array_sum(array_column($customers, 'totalPackage'));
            $totalPaid = array_sum(array_column($customers, 'paid'));
            $totalDue = array_sum(array_column($customers, 'due'));
        @endphp
        <div class="summary-row">
            <span class="label">Total Customers:</span>
            <span class="value">{{ count($customers) }}</span>
        </div>
        <div class="summary-row">
            <span class="label">Total Package Amount:</span>
            <span class="value">{{ number_format($totalPackage, 2) }}</span>
        </div>
        <div class="summary-row">
            <span class="label">Total Paid:</span>
            <span class="value">{{ number_format($totalPaid, 2) }}</span>
        </div>
        <div class="summary-row">
            <span class="label">Total Due:</span>
            <span class="value">{{ number_format($totalDue, 2) }}</span>
        </div>
    </div>
    @endif

    <div class="footer">
        <p>BM Umrah Booking System | Generated {{ now()->format('d-M-Y h:i A') }}</p>
    </div>
</body>
</html>
