<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profit/Loss Report - BM Umrah</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Courier New', monospace; font-size: 14px; padding: 10px; color: #000; }
        .header { text-align: center; margin-bottom: 12px; border-bottom: 2px solid #333; padding-bottom: 8px; }
        .header h1 { font-size: 20px; font-weight: bold; }
        .header p { font-size: 13px; color: #555; margin-top: 3px; }
        .print-info { display: flex; justify-content: space-between; font-size: 12px; margin-bottom: 8px; color: #555; }
        .filters-summary { font-size: 12px; margin-bottom: 10px; padding: 6px; border: 1px solid #ccc; background: #f9f9f9; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 10px; table-layout: auto; }
        th { background: #e0e0e0; font-size: 12px; font-weight: bold; text-align: center; padding: 5px 4px; border: 1px solid #999; white-space: nowrap; }
        td { font-size: 12px; padding: 4px 4px; border: 1px solid #ccc; }
        .text-left { text-align: left; }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .text-green { color: #15803d; }
        .text-red { color: #dc2626; }
        .grand-total { background: #e0e0e0; font-weight: bold; }
        .footer { text-align: center; font-size: 11px; color: #888; margin-top: 15px; border-top: 1px solid #ccc; padding-top: 6px; }
        @media print {
            body { padding: 5px; }
            .no-print { display: none; }
            @page { size: landscape; margin: 8mm; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Profit/Loss Report - {{ $type === 'customer' ? 'Per Customer' : 'Per Passenger' }}</h1>
        <p>BM Umrah Booking System</p>
    </div>

    <div class="print-info">
        <span>Generated: <span class="local-time"></span></span>
        <span>Generated by: {{ auth()->user()->name }}</span>
    </div>

    @php
        $__currency = $currency ?? 'SAR';
        $__rate = app(\App\Services\CurrencyRateService::class)->getCurrentRateValue();
        $fmtNum = function($amount, $d = 0) use ($__currency, $__rate) {
            if ($amount === null || $amount === '') return '';
            $val = $__currency === 'BDT' ? $amount * $__rate : $amount;
            return number_format($val, $d);
        };
        $fmtCurrency = function($amount, $d = 0) use ($__currency, $__rate) {
            if ($amount === null || $amount === '') return '';
            $val = $__currency === 'BDT' ? $amount * $__rate : $amount;
            return ($__currency === 'BDT' ? 'BDT ' : 'SAR ') . number_format($val, $d);
        };

        $appliedFilters = array_filter([
            'Date From' => $dateFrom,
            'Date To' => $dateTo,
            'Search' => $search ?? null,
            'Profit/Loss' => isset($profitLossFilter) && $profitLossFilter !== 'all' ? ucfirst($profitLossFilter) : null,
        ]);
    @endphp

    @if(!empty($appliedFilters))
    <div class="filters-summary">
        <strong>Filters Applied:</strong>
        @foreach($appliedFilters as $label => $value)
            <span>{{ $label }}: {{ $value }}@if(!$loop->last) | @endif</span>
        @endforeach
        <span> | Currency: {{ $__currency }}</span>
    </div>
    @endif

    @if($type === 'customer')
    <table>
        <thead>
            <tr>
                <th>Invoice ID</th>
                <th>Customer Name</th>
                <th>Mobile</th>
                <th>Pax Qty</th>
                <th>Package Value ({{ $__currency }})</th>
                <th>Fingerprint Profit</th>
                <th>Passenger Profit</th>
                <th>Discount</th>
                <th>Total Profit ({{ $__currency }})</th>
            </tr>
        </thead>
        <tbody>
            @forelse($customers as $row)
            <tr>
                <td class="text-left">{{ $row['invoice_id'] }}</td>
                <td class="text-left">{{ $row['customer_name'] }}</td>
                <td class="text-center">{{ $row['mobile'] }}</td>
                <td class="text-center">{{ $row['pax_qty'] }}</td>
                <td class="text-right">{{ $fmtCurrency($row['package_value']) }}</td>
                <td class="text-right {{ $row['fingerprint_profit'] >= 0 ? 'text-green' : 'text-red' }}">{{ ($row['fingerprint_profit'] >= 0 ? '+' : '') . $fmtCurrency($row['fingerprint_profit']) }}</td>
                <td class="text-right {{ $row['passenger_profit_total'] >= 0 ? 'text-green' : 'text-red' }}">{{ ($row['passenger_profit_total'] >= 0 ? '+' : '') . $fmtCurrency($row['passenger_profit_total']) }}</td>
                <td class="text-right">{{ $fmtCurrency($row['discount']) }}</td>
                <td class="text-right {{ $row['total_profit'] >= 0 ? 'text-green' : 'text-red' }}">{{ ($row['total_profit'] >= 0 ? '+' : '') . $fmtCurrency($row['total_profit']) }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="9" class="text-center" style="padding: 20px;">No records found.</td>
            </tr>
            @endforelse
            @if(count($customers) > 0)
            @php
                $gt = $summary['customer'] ?? [];
                $gtCount = $gt['count'] ?? count($customers);
            @endphp
            <tr class="grand-total">
                <td class="text-left" colspan="4">Grand Total ({{ $gtCount }} {{ $gtCount == 1 ? 'Customer' : 'Customers' }})</td>
                <td class="text-right">{{ $fmtCurrency($gt['package_value'] ?? 0) }}</td>
                <td class="text-right {{ ($gt['fingerprint_profit'] ?? 0) >= 0 ? 'text-green' : 'text-red' }}">{{ (($gt['fingerprint_profit'] ?? 0) >= 0 ? '+' : '') . $fmtCurrency($gt['fingerprint_profit'] ?? 0) }}</td>
                <td class="text-right {{ ($gt['passenger_profit_total'] ?? 0) >= 0 ? 'text-green' : 'text-red' }}">{{ (($gt['passenger_profit_total'] ?? 0) >= 0 ? '+' : '') . $fmtCurrency($gt['passenger_profit_total'] ?? 0) }}</td>
                <td class="text-right">{{ $fmtCurrency($gt['discount'] ?? 0) }}</td>
                <td class="text-right {{ ($gt['total_profit'] ?? 0) >= 0 ? 'text-green' : 'text-red' }}">{{ (($gt['total_profit'] ?? 0) >= 0 ? '+' : '') . $fmtCurrency($gt['total_profit'] ?? 0) }}</td>
            </tr>
            @endif
        </tbody>
    </table>
    @else
    <table>
        <thead>
            <tr>
                <th>Invoice ID</th>
                <th>Customer Name</th>
                <th>Mobile</th>
                <th>Passenger Name</th>
                <th>Package Value ({{ $__currency }})</th>
                <th>Total Profit ({{ $__currency }})</th>
            </tr>
        </thead>
        <tbody>
            @forelse($passengers as $row)
            @php
                $bd = $row['breakdown'] ?? [];
                $fmtSigned = fn($v) => ($v >= 0 ? '+' : '') . $fmtNum($v);
            @endphp
            <tr>
                <td class="text-left">{{ $row['invoice_id'] }}</td>
                <td class="text-left">{{ $row['customer_name'] }}</td>
                <td class="text-center">{{ $row['mobile'] }}</td>
                <td class="text-left">{{ $row['passenger_name'] }}</td>
                <td class="text-right">{{ $fmtCurrency($row['package_value']) }}</td>
                <td class="text-right {{ $row['total_profit'] >= 0 ? 'text-green' : 'text-red' }}">{{ ($row['total_profit'] >= 0 ? '+' : '') . $fmtCurrency($row['total_profit']) }}</td>
            </tr>
            <tr>
                <td colspan="6" class="text-left" style="font-size: 10px; color: #555; border-top: none; padding-top: 0;">
                    Visa: {{ $fmtSigned($bd['visa_profit'] ?? 0) }}
                    &nbsp;|&nbsp; Ticket: {{ $fmtSigned($bd['ticket_profit'] ?? 0) }}
                    &nbsp;|&nbsp; Additional: {{ $fmtSigned($bd['additional_ticket_profit'] ?? 0) }}
                    &nbsp;|&nbsp; Re-Issue Profit: {{ $fmtSigned($bd['re_issue_profit'] ?? 0) }}
                    &nbsp;|&nbsp; Refund Profit: {{ $fmtSigned($bd['refund_profit'] ?? 0) }}
                    &nbsp;|&nbsp; Re-Issue Cost: -{{ $fmtNum($bd['re_issue_cost'] ?? 0) }}
                    &nbsp;|&nbsp; Service Charge: {{ $fmtSigned($bd['service_charge'] ?? 0) }}
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="6" class="text-center" style="padding: 20px;">No records found.</td>
            </tr>
            @endforelse
            @if(count($passengers) > 0)
            @php
                $gt = $summary['passenger'] ?? [];
                $gtCount = $gt['count'] ?? count($passengers);
            @endphp
            <tr class="grand-total">
                <td class="text-left" colspan="4">Grand Total ({{ $gtCount }} {{ $gtCount == 1 ? 'Passenger' : 'Passengers' }})</td>
                <td class="text-right">{{ $fmtCurrency($gt['package_value'] ?? 0) }}</td>
                <td class="text-right {{ ($gt['total_profit'] ?? 0) >= 0 ? 'text-green' : 'text-red' }}">{{ (($gt['total_profit'] ?? 0) >= 0 ? '+' : '') . $fmtCurrency($gt['total_profit'] ?? 0) }}</td>
            </tr>
            @endif
        </tbody>
    </table>
    @endif

    <div class="footer">
        <p>BM Umrah Booking System | Generated <span class="local-time"></span></p>
    </div>
    <script>
        document.querySelectorAll('.local-time').forEach(function (el) {
            var d = new Date();
            var months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
            var h = d.getHours(), ap = h >= 12 ? 'PM' : 'AM';
            h = h % 12 || 12;
            var p = function (n) { return String(n).padStart(2, '0'); };
            el.textContent = p(d.getDate()) + '-' + months[d.getMonth()] + '-' + d.getFullYear() + ' ' + p(h) + ':' + p(d.getMinutes()) + ' ' + ap;
        });
    </script>
</body>
</html>
