<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ticket Statement - BM Umrah</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Courier New', monospace; font-size: 12px; padding: 10px; color: #000; }
        .header { text-align: center; margin-bottom: 10px; border-bottom: 2px solid #333; padding-bottom: 8px; }
        .header h1 { font-size: 20px; font-weight: bold; }
        .header p { font-size: 13px; color: #555; margin-top: 3px; }
        .print-info { display: flex; justify-content: space-between; font-size: 12px; margin-bottom: 8px; color: #555; }
        .filters-summary { font-size: 12px; margin-bottom: 10px; padding: 6px; border: 1px solid #ccc; background: #f9f9f9; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 10px; table-layout: auto; }
        th { background: #e0e0e0; font-size: 10px; font-weight: bold; padding: 4px 3px; border: 1px solid #999; white-space: nowrap; }
        td { font-size: 10px; padding: 3px 3px; border: 1px solid #ccc; }
        .text-left { text-align: left; }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .section-row td { background: #f0f0f0; font-weight: bold; font-size: 11px; padding: 5px 4px; }
        .footer { text-align: center; font-size: 11px; color: #888; margin-top: 15px; border-top: 1px solid #ccc; padding-top: 6px; }
        .print-btn { display: inline-block; margin-bottom: 10px; padding: 8px 20px; font-size: 14px; font-weight: bold; color: #fff; background: #334155; border: none; border-radius: 4px; cursor: pointer; }
        .print-btn:hover { background: #1e293b; }
        @media print {
            body { padding: 5px; }
            .no-print { display: none; }
            @page { size: landscape; margin: 8mm; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Ticket Statement</h1>
        <p>BM Umrah Booking System</p>
    </div>

    <div class="print-info">
        <span>Generated: <span class="local-time"></span></span>
        <span>Generated by: {{ auth()->user()->name }}</span>
    </div>

    @php
        $__currency = $currency ?? 'SAR';
        $__rate = (float) ($rate ?? 0);
        $fmtMoney = function ($v) use ($__currency, $__rate) {
            if ($v === null || $v === '') return '-';
            $val = ($__currency === 'BDT' && $__rate > 0) ? ((float) $v) * $__rate : (float) $v;
            return number_format($val, 2).' '.$__currency;
        };
        $dateLabel = ($dateFrom ?? '').' to '.($dateTo ?? '');
    @endphp

    <div class="no-print" style="text-align: right;">
        <button class="print-btn" onclick="window.print()">Print</button>
    </div>

    <div class="filters-summary">
        <strong>Filters Applied:</strong>
        <span>
            Date Type: {{ $dateType ?? 'issue' }}
            | Date: {{ $dateLabel }}
            @if($agentName) | Agent: {{ $agentName }} @endif
            @if($search) | Search: {{ $search }} @endif
            | Currency: {{ $__currency }}
        </span>
    </div>

    <table>
        <thead>
            <tr>
                <th class="text-left">Issue Date</th>
                <th class="text-left">Ticket No</th>
                <th class="text-left">PAX Name</th>
                <th class="text-left">PNR</th>
                <th class="text-left">Sector</th>
                <th class="text-left">Flight Date</th>
                <th class="text-right">Customer Amount</th>
                <th class="text-right">Agent Fare (Net)</th>
                <th class="text-right">MARKUP</th>
                <th class="text-right">Customer Refund</th>
                <th class="text-right">IATA Refund</th>
                <th class="text-right">Payment to IATA</th>
                <th class="text-right">Balance Agent</th>
                <th class="text-left">IATA Agent</th>
            </tr>
            <tr>
                <th class="text-left">Category</th>
                <th class="text-left">Reference ID</th>
                <th class="text-left">Customer Name</th>
                <th class="text-left">Passport</th>
                <th class="text-left">Carrier | Class</th>
                <th class="text-left">Return Date</th>
                <th colspan="7"></th>
                <th class="text-left">Ticket Staff</th>
            </tr>
        </thead>
        <tbody>
            @foreach($agents as $agent)
                @if(!$agent['has_rows'])
                    <tr class="section-row">
                        <td colspan="14">{{ $agent['agent_name'] }} — Opening B/L: {{ $fmtMoney($agent['opening_balance']) }}</td>
                    </tr>
                    <tr class="section-row">
                        <td colspan="14" class="text-right">{{ $agent['agent_name'] }} — Closing B/L: {{ $fmtMoney($agent['closing_balance']) }}</td>
                    </tr>
                @endif
            @endforeach
            @foreach($rows as $row)
                @if($row['agent_changed'])
                    <tr class="section-row">
                        <td colspan="14">{{ $agents[$row['agent_id']]['agent_name'] }} — Opening B/L: {{ $fmtMoney($agents[$row['agent_id']]['opening_balance']) }}</td>
                    </tr>
                @endif
                <tr>
                    <td>{{ $row['date'] }}</td>
                    <td>{{ $row['ticket_no'] }}</td>
                    <td>{{ $row['pax_name'] }}</td>
                    <td>{{ $row['pnr'] }}</td>
                    <td>{{ $row['sector'] }}</td>
                    <td>{{ $row['flight_date'] }}</td>
                    <td class="text-right" rowspan="2">{{ $fmtMoney($row['customer_amount']) }}</td>
                    <td class="text-right" rowspan="2">{{ $fmtMoney($row['agent_fare']) }}</td>
                    <td class="text-right" rowspan="2">{{ $fmtMoney($row['markup']) }}</td>
                    <td class="text-right" rowspan="2">{{ $fmtMoney($row['customer_refund']) }}</td>
                    <td class="text-right" rowspan="2">{{ $fmtMoney($row['iata_refund']) }}</td>
                    <td class="text-right" rowspan="2">{{ $fmtMoney($row['payment_to_iata']) }}</td>
                    <td class="text-right" rowspan="2" style="font-weight: bold;">{{ $fmtMoney($row['balance']) }}</td>
                    <td>{{ $row['agent_name'] }}</td>
                </tr>
                <tr>
                    <td>{{ $row['category'] }}</td>
                    <td>{{ $row['reference_id'] }}</td>
                    <td>{{ $row['customer_name'] }}</td>
                    <td>{{ $row['passport'] }}</td>
                    <td>{{ $row['carrier_class_pay'] }}</td>
                    <td>{{ $row['return_date'] }}</td>
                    <td>{{ $row['staff_name'] }}</td>
                </tr>
                @if($row['agent_ends'])
                    <tr class="section-row">
                        <td colspan="14" class="text-right">{{ $agents[$row['agent_id']]['agent_name'] }} — Closing B/L: {{ $fmtMoney($agents[$row['agent_id']]['closing_balance']) }}</td>
                    </tr>
                @endif
            @endforeach
            @if(count($rows) === 0 && count(array_filter($agents, fn ($a) => !$a['has_rows'])) === 0)
                <tr>
                    <td colspan="14" class="text-center" style="padding: 20px;">No records found.</td>
                </tr>
            @endif
        </tbody>
    </table>

    <div class="footer">
        <p>BM Umrah Booking System | Generated <span class="local-time"></span></p>
    </div>
    <script>
        document.querySelectorAll('.local-time').forEach(function (el) {
            var d = new Date();
            var months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
            var h = d.getHours(), ap = h >= 12 ? 'PM' : 'AM';
            h = h % 12 || 12;
            var p = function (n) { return String(n).padStart(2, '0'); };
            el.textContent = p(d.getDate()) + '-' + months[d.getMonth()] + '-' + d.getFullYear() + ' ' + p(h) + ':' + p(d.getMinutes()) + ' ' + ap;
        });
    </script>
</body>
</html>
