<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fingerprint Report - BM Umrah</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Courier New', monospace; font-size: 10px; padding: 15px; color: #000; }
        .header { text-align: center; margin-bottom: 15px; border-bottom: 2px solid #333; padding-bottom: 8px; }
        .header h1 { font-size: 16px; font-weight: bold; }
        .header p { font-size: 10px; color: #555; margin-top: 3px; }
        .print-info { display: flex; justify-content: space-between; font-size: 9px; margin-bottom: 10px; color: #555; }
        .filters-summary { font-size: 9px; margin-bottom: 10px; padding: 6px; border: 1px solid #ccc; background: #f9f9f9; }
        .filters-summary strong { font-size: 9px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        th { background: #e0e0e0; font-size: 8px; font-weight: bold; text-align: center; padding: 4px 3px; border: 1px solid #999; }
        td { font-size: 8px; padding: 3px; border: 1px solid #ccc; }
        .text-left { text-align: left; }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .text-green { color: #15803d; }
        .text-red { color: #dc2626; }
        .whitespace-pre-line { white-space: pre-line; }
        .summary { margin-top: 10px; border-top: 2px solid #333; padding-top: 8px; }
        .summary-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 4px 20px; }
        .summary-row { display: flex; justify-content: space-between; padding: 2px 0; font-size: 9px; }
        .summary-row.bordered { border-top: 1px solid #ccc; padding-top: 4px; margin-top: 2px; }
        .summary-row .label { font-weight: bold; }
        .summary-row .value { font-weight: bold; }
        .footer { text-align: center; font-size: 8px; color: #888; margin-top: 15px; border-top: 1px solid #ccc; padding-top: 6px; }
        .page-break { page-break-after: always; }
        .invoice-group { border-left: 3px solid #999; }
        .invoice-group-odd { border-left: 3px solid #2563eb; }
        .invoice-group-even { border-left: 3px solid #ea580c; }
        @media print {
            body { padding: 10px; }
            .no-print { display: none; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Fingerprint Report</h1>
        <p>BM Umrah Booking System</p>
    </div>

    <div class="print-info">
        <span>Generated: {{ now()->format('d-M-Y h:i A') }}</span>
        <span>Generated by: {{ auth()->user()->name }}</span>
    </div>

    @php
        $appliedFilters = array_filter([
            'Search' => request('search'),
            'Booking Date From' => request('booking_date_from'),
            'Booking Date To' => request('booking_date_to'),
            'Completion Date From' => request('completion_date_from'),
            'Completion Date To' => request('completion_date_to'),
            'Status' => request('status'),
            'Assigned Staff' => request('assigned_staff_id') ? \App\Models\User::find(request('assigned_staff_id'))?->name : null,
            'Location' => request('fingerprint_location'),
            'Branch' => request('branch_id') ? \App\Models\Branch::find(request('branch_id'))?->name : null,
            'District' => request('district_id') ? \App\Models\District::find(request('district_id'))?->name : null,
            'Office' => request('office_id') ? \App\Models\Office::find(request('office_id'))?->name : null,
        ]);
    @endphp

    @if(!empty($appliedFilters))
    <div class="filters-summary">
        <strong>Filters Applied:</strong>
        @foreach($appliedFilters as $label => $value)
            <span>{{ $label }}: {{ $value }}@if(!$loop->last) | @endif</span>
        @endforeach
    </div>
    @endif

    <table>
        <thead>
            <tr>
                <th>Invoice ID</th>
                <th>Customer Name</th>
                <th>Booking Date</th>
                <th>Passenger Name</th>
                <th>Passport No</th>
                <th>Mobile</th>
                @if($canViewFinancials)
                <th>Fingerprint Charge</th>
                @endif
                <th>Fingerprint Cost</th>
                <th>Fingerprint Deadline</th>
                <th>Completed Date</th>
                <th>Req. Flight</th>
                <th>Act. Flight</th>
                <th>Status</th>
                <th>Remarks</th>
                @if($canViewFinancials)
                <th>Profit/Loss</th>
                @endif
            </tr>
        </thead>
        <tbody>
            @forelse($items as $row)
            <tr style="{{ $row['_isLastPassenger'] ? 'border-bottom: 2px solid #666;' : '' }}">
                <td class="text-center">{{ $row['_isFirstPassenger'] ? $row['invoice_id'] : '' }}</td>
                <td class="text-left">{{ $row['_isFirstPassenger'] ? $row['customer_name'] : '' }}</td>
                <td class="text-center">{{ $row['_isFirstPassenger'] ? $row['booking_date'] : '' }}</td>
                <td class="text-left">{{ $row['passenger_name'] }}</td>
                <td class="text-center">{{ $row['passport_no'] }}</td>
                <td class="text-left" style="white-space: pre-line;">{{ $row['_isFirstPassenger'] ? $row['customer_mobile'] . "\n" . $row['passenger_mobile'] : $row['passenger_mobile'] }}</td>
                @if($canViewFinancials)
                <td class="text-right">{{ $row['_isFirstPassenger'] ? number_format($row['fingerprint_charge'], 2) : '' }}</td>
                @endif
                <td class="text-right">{{ $row['_isFirstPassenger'] ? number_format($row['fingerprint_cost'], 2) : '' }}</td>
                <td class="text-center">{{ $row['_isFirstPassenger'] ? ($row['fingerprint_deadline'] ?? '-') : '' }}</td>
                <td class="text-center">{{ $row['completed_date'] ?? '-' }}</td>
                <td class="text-left">{{ $row['required_flight'] ?? '-' }}</td>
                <td class="text-left">{{ $row['actual_flight'] ?? '-' }}</td>
                <td class="text-center">{{ $row['status_display'] ?? '-' }}</td>
                <td class="text-left">{{ $row['remarks'] ?? '-' }}</td>
                @if($canViewFinancials)
                <td class="text-right {{ ($row['profit_loss'] ?? 0) >= 0 ? 'text-green' : 'text-red' }}">{{ $row['_isFirstPassenger'] ? number_format($row['profit_loss'], 2) : '' }}</td>
                @endif
            </tr>
            @empty
            <tr>
                <td colspan="15" class="text-center" style="padding: 20px;">No records found.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="summary">
        <div class="summary-grid">
            <div class="summary-row">
                <span class="label">Total Invoices:</span>
                <span class="value">{{ $totals['total_invoices'] }}</span>
            </div>
            <div class="summary-row">
                <span class="label">Total PAX:</span>
                <span class="value">{{ $totals['total_pax'] }}</span>
            </div>
            @if($canViewFinancials)
            <div class="summary-row">
                <span class="label">Total Fingerprint Charge:</span>
                <span class="value text-green">{{ number_format($totals['total_fingerprint_charge'], 2) }} SAR</span>
            </div>
            @endif
            <div class="summary-row">
                <span class="label">Total Fingerprint Cost:</span>
                <span class="value">{{ number_format($totals['total_fingerprint_cost'], 2) }} SAR</span>
            </div>
            @if($canViewFinancials)
            <div class="summary-row">
                <span class="label">Total Profit:</span>
                <span class="value {{ $totals['total_profit_loss'] >= 0 ? 'text-green' : '' }}">{{ $totals['total_profit_loss'] >= 0 ? number_format($totals['total_profit_loss'], 2) . ' SAR' : '-' }}</span>
            </div>
            <div class="summary-row">
                <span class="label">Total Loss:</span>
                <span class="value text-red">{{ $totals['total_profit_loss'] < 0 ? number_format(abs($totals['total_profit_loss']), 2) . ' SAR' : '-' }}</span>
            </div>
            <div class="summary-row bordered">
                <span class="label">Net Profit/Loss:</span>
                <span class="value {{ $totals['total_profit_loss'] >= 0 ? 'text-green' : 'text-red' }}">{{ number_format($totals['total_profit_loss'], 2) }} SAR</span>
            </div>
            @endif
        </div>
    </div>

    <div class="footer">
        <p>BM Umrah Booking System | Generated {{ now()->format('d-M-Y h:i A') }}</p>
    </div>
</body>
</html>
