<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment History - BM Umrah</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Courier New', monospace; font-size: 14px; padding: 10px; color: #000; }
        .header { text-align: center; margin-bottom: 12px; border-bottom: 2px solid #333; padding-bottom: 8px; }
        .header h1 { font-size: 20px; font-weight: bold; }
        .header p { font-size: 13px; color: #555; margin-top: 3px; }
        .print-info { display: flex; justify-content: space-between; font-size: 12px; margin-bottom: 8px; color: #555; }
        .filters-summary { font-size: 12px; margin-bottom: 10px; padding: 6px; border: 1px solid #ccc; background: #f9f9f9; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 10px; table-layout: auto; }
        th { background: #e0e0e0; font-size: 11px; font-weight: bold; text-align: center; padding: 5px 4px; border: 1px solid #999; white-space: nowrap; }
        td { font-size: 11px; padding: 4px 4px; border: 1px solid #ccc; }
        .text-left { text-align: left; }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .method-cash { color: #15803d; font-weight: bold; }
        .method-bank { color: #2563eb; font-weight: bold; }
        .summary { margin-top: 10px; border-top: 2px solid #333; padding-top: 8px; }
        .summary-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 4px 20px; }
        .summary-row { display: flex; justify-content: space-between; padding: 2px 0; font-size: 12px; }
        .summary-row .label { font-weight: bold; }
        .summary-row .value { font-weight: bold; }
        .footer { text-align: center; font-size: 11px; color: #888; margin-top: 15px; border-top: 1px solid #ccc; padding-top: 6px; }
        .date-group-header { background: #f0f0f0; font-weight: bold; font-size: 11px; }
        .date-group-header td { padding: 4px 6px; border-bottom: 2px solid #999; }
        @media print {
            body { padding: 5px; }
            .no-print { display: none; }
            @page { size: landscape; margin: 8mm; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Payment History</h1>
        <p>BM Umrah Booking System</p>
    </div>

    <div class="print-info">
        <span>Generated: <span class="local-time"></span></span>
        <span>Generated by: {{ auth()->user()->name }}</span>
    </div>

    @php
        $__currency = $currency ?? 'SAR';
        $fmtNum = function($amount, $bdtAmount = 0) use ($__currency) {
            if ($amount === null || $amount === '') return '';
            $val = ($__currency === 'BDT' && $bdtAmount > 0) ? $bdtAmount : $amount;
            $val = floor($val * 100) / 100;
            return number_format($val, 2);
        };
        $fmtCurrency = function($amount, $bdtAmount = 0) use ($__currency) {
            if ($amount === null || $amount === '') return '';
            $val = ($__currency === 'BDT' && $bdtAmount > 0) ? $bdtAmount : $amount;
            $val = floor($val * 100) / 100;
            return ($__currency === 'BDT' ? 'BDT ' : 'SAR ') . number_format($val, 2);
        };
    @endphp

    <div class="filters-summary">
        <strong>Filters Applied:</strong>
        <span>
            Date Range: {{ $dateLabel }}
            @if($branch) | Branch: {{ $branch->name }}@endif
            @if($bankName) | Bank: {{ $bankName }}@endif
            @if($methodLabel) | Method: {{ $methodLabel }}@endif
            | Currency: {{ $__currency }}
        </span>
    </div>

    @php
        $vouchersByDate = $vouchers->groupBy(function($v) {
            return \Carbon\Carbon::parse($v['payment_date'] ?? now())->format('Y-m-d');
        })->sortKeys();
    @endphp

    <table>
        <thead>
            <tr>
                <th>Invoice ID</th>
                <th>Voucher No</th>
                <th>Method</th>
                <th>Bank Name</th>
                <th>Transaction Type</th>
                <th>Trx ID</th>
                <th>Receive By</th>
                <th>Receive At</th>
                <th>Payment Date</th>
                <th style="text-align: right">Amount</th>
            </tr>
        </thead>
        <tbody>
            @forelse($vouchersByDate as $date => $dateVouchers)
                <tr class="date-group-header">
                    <td colspan="10">{{ \Carbon\Carbon::parse($date)->format('d-M-Y') }}</td>
                </tr>
                @foreach($dateVouchers as $v)
                <tr>
                    <td class="text-center">{{ $v['invoice_id'] }}</td>
                    <td class="text-center">{{ $v['voucher_no'] }}</td>
                    <td class="text-center {{ $v['method'] === 'Cash' ? 'method-cash' : 'method-bank' }}">{{ $v['method'] }}</td>
                    <td class="text-left">{{ $v['bank'] ?? '-' }}</td>
                    <td class="text-left">{{ $v['transaction_type'] }}</td>
                    <td class="text-left">{{ $v['trx_id'] }}</td>
                    <td class="text-left">{{ $v['receive_by'] }}</td>
                    <td class="text-left">{{ $v['receive_at'] }}</td>
                    <td class="text-center">{{ $v['payment_date'] }}</td>
                     <td class="text-right" style="font-weight: bold">{{ $fmtNum($v['amount'], $v['bdt_amount'] ?? 0) }}</td>
                </tr>
                @endforeach
            @empty
            <tr>
                <td colspan="10" class="text-center" style="padding: 20px;">No records found.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="summary">
        <div class="summary-grid">
            <div class="summary-row">
                <span class="label">Cash Total:</span>
                <span class="value" style="color: #15803d">{{ $fmtCurrency($totalCash, $totalCashBdt ?? 0) }}</span>
            </div>
            <div class="summary-row">
                <span class="label">Bank Total:</span>
                <span class="value" style="color: #2563eb">{{ $fmtCurrency($totalBank, $totalBankBdt ?? 0) }}</span>
            </div>
            <div class="summary-row">
                <span class="label">Grand Total:</span>
                <span class="value">{{ $fmtCurrency($totalAmount, $totalAmountBdt ?? 0) }}</span>
            </div>
        </div>
    </div>

    <div class="footer">
        <p>BM Umrah Booking System | Generated <span class="local-time"></span></p>
    </div>
    <script>
        document.querySelectorAll('.local-time').forEach(function (el) {
            var d = new Date();
            var months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
            var h = d.getHours(), ap = h >= 12 ? 'PM' : 'AM';
            h = h % 12 || 12;
            var p = function (n) { return String(n).padStart(2, '0'); };
            el.textContent = p(d.getDate()) + '-' + months[d.getMonth()] + '-' + d.getFullYear() + ' ' + p(h) + ':' + p(d.getMinutes()) + ' ' + ap;
        });
    </script>
</body>
</html>
